#ifndef __STRUTILS_H
#define __STRUTILS_H

/**
 * This function generates a new string by concatenating multiple strings
 * together.  The function is variadic, so any number of strings can be passed.
 * A new string is generated by concatenating the passed strings in order.
 *
 * @param n The total number of strings passed as variadic arguments.
 * @param ... A total of `n` of `char*` arguments, which are concatenated
 *   together in order to generate the returned string.
 *
 * @return The string generated by concatenating all arguments in order is
 *   returned.  Memory is allocated for the returned string, which must be
 *   freed by the caller.
 */
char* concat_strings(const int n, ...);

/**
 * Converts a floating point number to a string.
 *
 * @param val The floating point value to be converted to a string.
 *
 * @return Returns a string corresponding to `val`. Memory for the string is
 *   allocated by this function and must be freed by the caller.
 */
char* float_to_str(float val);

/**
 * Converts an integer number to a string.
 *
 * @param val The integer value to be converted to a string.
 *
 * @return Returns a string corresponding to `val`. Memory for the string is
 *   allocated by this function and must be freed by the caller.
 */
char* int_to_str(int val);

#endif
