#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>

/*
 * This function generates a new string by concatenating multiple strings
 * together.  The function is variadic, so any number of strings can be passed.
 * A new string is generated by concatenating the passed strings in order.
 *
 * @param n The total number of strings passed as variadic arguments.
 * @param ... A total of `n` of `char*` arguments, which are concatenated
 *   together in order to generate the returned string.
 *
 * @return The string generated by concatenating all arguments in order is
 *   returned.  Memory is allocated for the returned string, which must be
 *   freed by the caller.
 */
char* concat_strings(const int n, ...) {
    int l = 0;
    char* strings[n];

    /*
     * Loop through the arguments to calculate the total length, and remember
     * the string pointers.
     */
    va_list args;
    va_start(args, n);
    for (int i = 0; i < n; i++) {
        strings[i] = va_arg(args, char*);
        l += strlen(strings[i]);
    }

    /*
     * Concatenate all strings together into one.
     */
    char* result = malloc((l + 1) * sizeof(char));
    result[0] = '\0';
    for (int i = 0; i < n; i++) {
        strncat(result, strings[i], l);
        l -= strlen(strings[i]);
    }
    return result;
}

/*
 * Converts a floating point number to a string.
 *
 * @param val The floating point value to be converted to a string.
 *
 * @return Returns a string corresponding to `val`. Memory for the string is
 *   allocated by this function and must be freed by the caller.
 */
char* float_to_str(float val) {
    /*
     * snprintf() returns the number of characters that *would have* been
     * printed if an unlimited number of characters *could have* been printed.
     * Here, we use this feature to figure out how much space to allocate for
     * the string.
     */
    int l = snprintf(NULL, 0, "%f", val);
    char* str = malloc((l + 1) * sizeof(char));
    snprintf(str, l + 1, "%f", val);
    return str;
}

/*
 * Converts an integer number to a string.
 *
 * @param val The integer value to be converted to a string.
 *
 * @return Returns a string corresponding to `val`. Memory for the string is
 *   allocated by this function and must be freed by the caller.
 */
char* int_to_str(int val) {
    /*
     * snprintf() returns the number of characters that *would have* been
     * printed if an unlimited number of characters *could have* been printed.
     * Here, we use this feature to figure out how much space to allocate for
     * the string.
     */
    int l = snprintf(NULL, 0, "%d", val);
    char* str = malloc((l + 1) * sizeof(char));
    snprintf(str, l + 1, "%d", val);
    return str;
}
